pipeline:
  publish:
    image: plugins/docker
    repo: gboo/drone-wait-file
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push